version: 2.1
jobs:
  pull-and-build:
    docker:
      - image: cimg/node:17.3.0
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./deploy.sh"
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP_STAGING "./deploy.sh"
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP_DEVELOP "./deploy.sh"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main
                - staging
                - develop
