import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Max Awad 💻📸🛫</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the world of Max Awad!</h1>

        <p className={styles.description}>
          Get started by checking out my{' '}
          <a href="https://instagram.com/max_acting_up" target="_blank">
            📸 Instagram <code className={styles.code}>@max_acting_up</code>
          </a>
        </p>

        <div className={styles.grid}>
          <a
            href="mailto:max@maxawad.com?subject=I%20wanted%20to%20reach%20out!"
            className={styles.card}
          >
            <h2>Email me &rarr;</h2>
            <p>Click to start composing an email on your favorite app. </p>
          </a>

          <a href="https://nohello.com/" className={styles.card}>
            <h2>No hello &rarr;</h2>
            <p>Learn about some standards in communications!</p>
          </a>

          <a href="https://googlemaps.com" className={styles.card}>
            <h2>Where is Max? &rarr;</h2>
            <p>
              Click to open a world map to find out where I am right now. [Work
              in progress]
            </p>
          </a>

          <a href="/ski" className={styles.card}>
            <h2>Max and the snow 🎿 &rarr;</h2>
            <p>
              Read through a few of my accomplishments and goals for my skiing
              careers.
            </p>
          </a>

          <a href="https://linkedin.com/in/maxawad" className={styles.card}>
            <h2>LinkedIn &rarr;</h2>
            <p>
              Find out what I have been doing for the past 10 years. I am
              currently working for software firms.
            </p>
          </a>

          <a href="https://redxam.com" className={styles.card}>
            <h2>Crypto Bank &rarr;</h2>
            <p>
              During the 2020 lockdown, I decided to create a bank that has no
              borders or lockdowns.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by love ❤️ and tech 💾
        </a>
      </footer>
    </div>
  );
}
