import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the world of Max Awad!</h1>

        <p className={styles.description}>
          Get started by checking out my 📸 Instagram{' '}
          <code className={styles.code}>
            <a href="https://instagram.com/max_in_ecu">@max_in_ecu</a>
          </code>
        </p>

        <div className={styles.grid}>
          <a
            href="mailto:max@maxawad.com?subject=I%20wanted%20to%20reach%20out!"
            className={styles.card}
          >
            <h2>Email me &rarr;</h2>
            <p>Click to start composing an email on your favorite app. </p>
          </a>

          <a href="https://bitcoin.org/" className={styles.card}>
            <h2>Learn about Crypto &rarr;</h2>
            <p>Learn about bitcoin and other cryptocurrency!</p>
          </a>

          <a href="https://googlemaps.com" className={styles.card}>
            <h2>Where is Max? &rarr;</h2>
            <p>
              Click to open a world map to find out where I am right now. [Work
              in progress]
            </p>
          </a>

          <a href="https://linkedin.com/in/maxawad" className={styles.card}>
            <h2>LinkedIn &rarr;</h2>
            <p>Find out what I have been doing for the past 10 years.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by love ❤️ and tech 💾
        </a>
      </footer>
    </div>
  );
}
