name: Develop Auto-PR
on:
  schedule:
    - cron:  '30 5,17 * * *'

jobs:
  pull-request:
    name: Open PR to staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "staging"
        pr_title: "Pulling ${{ github.ref }} into staging"
        pr_body: "👑 *An automated PR*"
        pr_reviewer: "maxawad"
        pr_draft: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
